---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssp-deploy
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: bharamicrosystems/nginx:v1
        ports:
        - containerPort: 80
