---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-app
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: qa-app
        image: bharamicrosystems/nginx:v1
        ports:
        - containerPort: 80
